security:
    encoders:
        App\Entity\Usuario: plaintext


    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        user_db:
            entity: { class: App\Entity\Usuario, property: codigoUsuarioPk }

    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /acceso
                check_path: /acceso
                remember_me: false
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true

    access_control:
        - { path: /api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /acceso, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, roles: IS_AUTHENTICATED_FULLY }